version: '3.9'
services:
  frontend:
    build: ./frontend
    container_name: app_frontend
    command: >
      sh -c "npm run build && npm run serve"
    restart: always
    ports:
      - 8080:8080
    working_dir: /app-frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:8080"]
      timeout: 10s
      retries: 5
  backend:
    container_name: app_backend
    build: ./backend
    tty: true
    stdin_open: true
    command: >
      sh -c "npm run db:reset && npm run dev"
    restart: always
    ports:
      - 3001:3001
    working_dir: /app-backend
    volumes:
      - ./backend:/app-backend
    depends_on:
      db:
        condition: service_healthy  
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_HOST: db
      MYSQL_DATABASE: cashforce_v3
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    container_name: database
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./database:/app-database
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    